const ciMonthCount          = 12;
      ciWeekDayCount        = 7;
      ciMaxSecond           = 59;
      ciMaxMinute           = 59;
      ciMaxHour             = 23;
      ciMicroWidth          = 8;
      ciMicroHeight         = 8;
      ciNoTimeDateLeft      = 9;
      ciDefaultTimeColor    = clNavy;
      ciDefaultDateColor    = clGreen;

      {
      ciNormalTimeWidth     = 80;
      ciNormalDateLeft      = 112;
      }
      csIniFileName         = 'lclock2.ini';
      csWinIniFileName      = 'windows.ini';

      csEtcFolder           = 'etc'+DirectorySeparator;
      csLocaleFolder        = 'locale'+DirectorySeparator;
      csConfigSection       = 'config';
      csMainSection         = 'main';
      csStickyFlag          = 'stickyflag';
      csStickyMargin        = 'stickymargin';
      csTransparentFlag     = 'transparentflag';
      csTransparentValue    = 'transparentvalue';
      csMinimizeBtnVisible  = 'minimizevisibleflag';
      csCloseBtnVisible     = 'closevisibleflag';
      csVisibleTimeFlag     = 'visibletimeflag';
      csVisibleDateFlag     = 'visibledateflag';
      csTimeFontValue       = 'timefontvalue';
      csDateFontValue       = 'datefontvalue';
      csTimeColorValue      = 'timecolorvalue';
      csDateColorValue      = 'datecolorvalue';
      csThemeNameValue      = 'themenamevalue';

      csDefaultTimeFont     = 'Verdana;1;-15;D;12;0';
      csDefaultDateFont     = 'Verdana;1;-15;D;12;0';

      csProgramName         = 'LClock';
      csVersion             = '0.0.1';

      //***** Темы
      csThemeFolder         = 'themes'+DirectorySeparator;
      csDefaultThemeName    = 'default.ini';
      csMicroSection        = 'micro';
      csDefaultMicroFolder  = 'pixmaps'+DirectorySeparator+'micro'+DirectorySeparator+'rounded'+DirectorySeparator;
      csButtonsSection      = 'buttons';
      csDefaultButtonFolder = 'pixmaps'+DirectorySeparator+'buttons'+DirectorySeparator+'oxygen'+DirectorySeparator;

      //***** Локаль
      csMainLocaleFilename  = 'main.ini';
      csFormsLocaleFilename = 'forms.ini';
      csMainPopUpItemSetup  = 'PopUpItem_Config';
      csMainPopUpItemExit   = 'PopUpItem_Exit';

