const ciMonthCount          = 12;
      ciWeekDayCount        = 7;
      ciMaxSecond           = 59;
      ciMaxMinute           = 59;
      ciMaxHour             = 23;
      ciMicroWidth          = 8;
      ciMicroHeight         = 8;


      csIniFileName         = 'lclock2.ini';
      csWinIniFileName      = 'windows.ini';

      csEtcFolder           = 'etc'+ccSlashChar;
      csLocaleFolder        = 'locale'+ccSlashChar;
      csConfigSection       = 'config';
      csStickyFlag          = 'stickyflag';
      csStickyMargin        = 'stickymargin';

      csProgramName         = 'LClock';
      csVersion             = '0.0.1';

      //***** Темы
      csThemeFolder         = 'themes'+ccSlashChar;
      csMicroSection        = 'micro';
      csDefaultMicroFolder  = 'pixmaps'+ccSlashChar+'micro'+ccSlashChar+'rounded'+ccSlashChar;
      csButtonsSection      = 'buttons';
      csDefaultButtonFolder = 'pixmaps'+ccSlashChar+'buttons'+ccSlashChar+'oxygen'+ccSlashChar;

      //***** Локаль
      csMainLocaleFilename  = 'main.ini';
      csFormsLocaleFilename = 'forms.ini';
      csMainPopUpItemSetup  = 'PopUpItem_Config';
      csMainPopUpItemExit   = 'PopUpItem_Exit';
